Esourcing.UI/Controllers/AuctionController.cs
using Esourcing.UI.Clients;
using Esourcing.UI.Models;
using ESourcing.Core.Repository;
using ESourcing.Core.ResultModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Esourcing.UI.Controllers
{
    public class AuctionController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly ProductClient _productClient;
        private readonly AuctionClient _auctionClient;
        private readonly BidClient _bidClient;

        public AuctionController(IUserRepository userRepository, ProductClient productClient, AuctionClient auctionClient, BidClient bidClient)
        {
            _userRepository = userRepository;
            _productClient = productClient;
            _auctionClient = auctionClient;
            _bidClient = bidClient;
        }

        public async Task<IActionResult> Index()
        {
            var auctions = await _auctionClient.GetAuctions();
            if (auctions.IsSuccess)
            {
                return View(auctions.Data);
            }
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var userList = await _userRepository.GetAllAsync();
            var productList = await _productClient.GetProducts();
            ViewBag.ProductList = productList.Data;
            ViewBag.UserList = userList;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuctionModel model)
        {
            model.Status = 0;
            model.CreatedAt = DateTime.Now;
            model.IncludedSellers.Add(model.SellerId);
            var createAuction = await _auctionClient.CreateAuction(model);
            if (createAuction.IsSuccess)
                return RedirectToAction("Index");
            return View(model);
        }

        public async Task<IActionResult> Detail(string id)
        {
            AuctionBidModel model = new AuctionBidModel();

            var auctionResponse = await _auctionClient.GetAuctionById(id);
            var bidsResponse = await _bidClient.GetAllBidsByAuctionId(id);


            model.SellerUserName = HttpContext.User?.Identity.Name;
            model.AuctionId = auctionResponse.Data.Id;
            model.ProductId = auctionResponse.Data.ProductId;
            model.Bids = bidsResponse.Data;
            var isAdmin = HttpContext.Session.GetString("IsAdmin");
            model.IsAdmin = Convert.ToBoolean(isAdmin);
            return View(model);
        }

        [HttpPost]
        public async Task<Result<string>> SendBid(BidModel model)
        {
            model.CreateAt = DateTime.Now;
            var sendBidResponse = await _bidClient.SendBid(model);
            return sendBidResponse;
        }

        [HttpPost]
        public async Task<Result<string>> ComPleteBid(string id)
        {
            var completeBidResponse = await _auctionClient.CompleteBid(id);
            return completeBidResponse;
        }


    }
}

Esourcing.UI/Views/Auction/Create.cshtml
@model AuctionModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="card card-primary card-outline">
        <div class="card-body">
            <h4>Auction Create Page Step</h4>
            <div class="row">
                <div class="col-5 col-sm-3">
                    <div class="nav flex-column nav-tabs h-100" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
                        <a class="nav-link active" id="vert-tabs-home-tab" data-toggle="pill" href="#vert-tabs-home" role="tab" aria-controls="vert-tabs-home" aria-selected="true">General Info</a>
                        <a class="nav-link" id="vert-tabs-profile-tab" data-toggle="pill" href="#vert-tabs-profile" role="tab" aria-controls="vert-tabs-profile" aria-selected="false">Product Select</a>
                        <a class="nav-link" id="vert-tabs-messages-tab" data-toggle="pill" href="#vert-tabs-messages" role="tab" aria-controls="vert-tabs-messages" aria-selected="false">Seller Select</a>

                    </div>
                </div>
                <div class="col-7 col-sm-9">
                    <div class="tab-content" id="vert-tabs-tabContent">

                        <div id="vert-tabs-home" class="text-left show active tab-pane fade card card-primary" role="tabpanel" aria-labelledby="vert-tabs-home-tab">
                            <div class="card-header">
                                <h3 class="card-title">General Info Inputs</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="Name">Auction Name</label>
                                    @Html.TextBoxFor(x => x.Name, new { placeholder = "Enter Auction Name", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label for="Description">Auction Description</label>
                                    @Html.TextBoxFor(x => x.Description, new { placeholder = "Enter Auction Description", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label for="Description">Auction Quantity</label>
                                    @Html.TextBoxFor(x => x.Quantity, new { placeholder = "Enter Quantity", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Start Date:</label>
                                    <div class="input-group date" id="StartedAt" data-target-input="nearest">
                                        <input type="text" asp-for="StartedAt" class="form-control datetimepicker-input" data-target="#StartedAt" />
                                        <div class="input-group-append" data-target="#StartedAt" data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Finish Date:</label>
                                    <div class="input-group date" id="FinishedAt" data-target-input="nearest">
                                        <input type="text" asp-for="FinishedAt" class="form-control datetimepicker-input" data-target="#FinishedAt" />
                                        <div class="input-group-append" data-target="#FinishedAt" data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="text-left tab-pane fade card card-warning" id="vert-tabs-profile" role="tabpanel" aria-labelledby="vert-tabs-profile-tab">
                            <div class="card-header">
                                <h3 class="card-title">Product Info Input</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.DropDownListFor(l => l.ProductId, new SelectList(ViewBag.ProductList, "Id", "Name"), "Please Select Product", new { @class = "custom-select form-control col-sm-6" })
                                </div>
                            </div>
                        </div>
                        <div class="text-left tab-pane fade card card-danger" id="vert-tabs-messages" role="tabpanel" aria-labelledby="vert-tabs-messages-tab">
                            <div class="card-header">
                                <h3 class="card-title">Seller Info Input</h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.DropDownListFor(l => l.SellerId, new SelectList(ViewBag.UserList, "Id", "FirstName"), "Please Select Seller", new { @class = "custom-select form-control col-sm-6" })
                                </div>
                                <div class="clearfix form-actions">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Create Auction" class="btn btn-info col-xs-3" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>

Esourcing.UI/Views/Auction/Detail.cshtml
@model AuctionBidModel
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

<div class="row">
    <div class="col-md-6">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Quick Auction</h3>
            </div>

            <div class="card-body">
                <div class="form-group">
                    <label for="exampleInputPrice">Price</label>
                    <input type="number" min="0" class="form-control" id="exampleInputPrice" placeholder="Enter Price" />
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" id="sendButton" class="btn btn-primary">Submit</button>
                @if (Model.IsAdmin)
                {
                    <button type="submit" id="finishButton" class="btn btn-primary">Finish RFQ</button>
                }
            </div>
        </div>
    </div>
    @Html.HiddenFor(x => x.AuctionId)
    @Html.HiddenFor(x => x.ProductId)
    @Html.HiddenFor(x => x.SellerUserName)
    <div class="col-md-6">
        <div class="card-header" style="background-color:darkgray">
            <h3 class="card-title">Active RFQ Detail</h3>
        </div>

        <div class="card-body">
            <table id="exampleAuction" class="table table-bordered table-hover">
                <thead>
                    <tr style="background-color:darkgray">
                        <th>RFQ User Name</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody class="bidLine">
                    <tr>
                        <th>Berkay</th>
                        <th>10</th>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>
<button type="submit" id="finishButton" class="btn btn-primary">Finish RFQ</button>

<script src="~/lib/microsoft-signalr/signalr.js"></script>
@*<script src="~/js/Views/RFQ/detail.js"></script>*@
<script src="~/js/detail.js"></script>

Esourcing.UI/Views/Auction/Index.cshtml
@model IEnumerable<AuctionModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Active Auction List</h3>
            </div>
            <div class="card-body">
                <table id="example1" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Quantity</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.Description</td>
                                <td>@item.Quantity</td>
                                <td>@item.StartedAt.ToShortDateString()</td>
                                <td>@item.FinishedAt.ToShortDateString()</td>
                                <td>
                                    @if (item.Status == 1)
                                    {
                                        <a asp-route-Id="@item.Id" class="btn btn-danger">Closed</a>
                                    }
                                    else
                                    {
                                        <a asp-controller="Auction" asp-action="Detail" asp-route-Id="@item.Id" class="btn btn-warning">Detail</a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>